services:
  - type: web
    name: spotify-dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt && cd spotify-profile-demo && npm install && npm run build"
    startCommand: "python main.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: SESSION_SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
